version: '3.1'
services:
  #########
  # Nginx #
  #########
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - './:/var/www/service'
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/service.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - '82:80'
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    links:
      - php-fpm
    labels:
      NAME: nginx
    networks:
      internal:
        aliases:
          - hello.local

  ###########
  # PHP FPM #
  ###########
  php-fpm:
    build:
      context: ./docker/php
    restart: unless-stopped
    environment:
      # https://blog.denisbondar.com/post/phpstorm_docker_xdebug
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/service:delegated
      - '${XDEBUG_INI}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    ports:
        - "${XDEBUG_PORT}"
    networks:
        - internal

volumes:
  of-composer:
  schemas:
    external: false
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: "${SUBNET}"

